const express = require('express')
const router = express.Router()
const AuthController = require("../controllers/AuthController")
const CheckLogin = require("../apifunctions/CheckLogin")
const finduser = require("../apifunctions/finduser")
const setpfp = require("../apifunctions/setpfp")
const OpenCapsule = require("../apifunctions/opencapsule")
const selltrian = require('../apifunctions/selltrian')
const post = require("../apifunctions/jsonstore")
const likepost = require('../apifunctions/likepost')
const setusername = require('../apifunctions/changeusername')
const ifuser = require("../apifunctions/checkifuser")
const totaluser = require("../apifunctions/totalusers")
const setpassword = require("../apifunctions/changepassword")
const newrole = require("../apifunctions/setrole")
const auction = require("../apifunctions/auction")
const authenticate = require('../middleware/authenticate')
const rateLimit = require('express-rate-limit')
const limiter = rateLimit({
    max: 1,
    windowMs: 1000,
    message: JSON.stringify({"error":"Rate Limit"})
})
router.post('/register', limiter,AuthController.register)
router.post('/login', limiter,AuthController.login)
router.post('/check-login', CheckLogin.CheckLogin)
router.post('/open', limiter,authenticate,OpenCapsule.opencapsule)
router.post('/sell', limiter,authenticate,selltrian.selltrian)
router.post('/like',limiter,authenticate,likepost.likepost)
router.post('/setrole',limiter,authenticate,newrole.setrole)
//router.post('/addauction',limiter,authenticate,auction.addauction)
//router.post('/bid',limiter,authenticate,auction.bid)
router.post('/bot/ifuser',ifuser.ifuser)
router.post('/bot/totalusers',totaluser.totaluser)
router.post('/finduser',finduser.finduser)
router.post("/setpfp",limiter,authenticate,setpfp.setpfp)
router.post("/setusername",limiter,authenticate,setusername.setusername)
router.post("/post",authenticate,post.storedata)
router.post("/setpassword",limiter,authenticate,setpassword.setpassword)
module.exports = router